### ISSUE TITLE
Process picker doesn't work with non-local ADB

### ISSUE THREAD

**Issue by the-ress** [adelphes/android-dev-ext#154]
The process picker doesn't respect the `adbSocket` option. (I'm running VS in a devcontainer.)

# Setup
Extension: `v1.4.0`

```
Version: 1.95.3 (system setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z (2 wks ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

# Config
```
{
  "type": "android",
  "request": "attach",
  "name": "Android Attach",
  "appSrcRoot": "${workspaceRoot}/app/src/main",
  "adbSocket": "host.docker.internal:5037",
  "processId": "${command:PickAndroidProcess}"
}
```

# Error
```
ADBSocket Socket connect failed. connect ECONNREFUSED 127.0.0.1:5037. Error: 
	at ADBSocket.connect (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/sockets/androidsocket.js:18:30)
	at ADBClient.connect_to_adb (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/adbclient.js:360:31)
	at ADBClient.list_devices (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/adbclient.js:139:20)
	at selectTargetDevice (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/utils/device.js:33:43)
	at /root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/extension.js:161:38
	at Y0.h (file:///vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
...
```

**Comment by Sonia19782004** [comment]
> El selector de procesos no respeta la `adbSocket`opción. (Estoy ejecutando VS en un contenedor de desarrollo).
> 
> # Configuración
> Extensión:`v1.4.0`
> 
> ```
> Version: 1.95.3 (system setup)
> Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
> Date: 2024-11-13T14:50:04.152Z (2 wks ago)
> Electron: 32.2.1
> ElectronBuildId: 10427718
> Chromium: 128.0.6613.186
> Node.js: 20.18.0
> V8: 12.8.374.38-electron.0
> OS: Windows_NT x64 10.0.22631
> ```
> 
> # Configuración
> ```
> {
>   "type": "android",
>   "request": "attach",
>   "name": "Android Attach",
>   "appSrcRoot": "${workspaceRoot}/app/src/main",
>   "adbSocket": "host.docker.internal:5037",
>   "processId": "${command:PickAndroidProcess}"
> }
> ```
> 
> # Error
> ```
> ADBSocket Socket connect failed. connect ECONNREFUSED 127.0.0.1:5037. Error: 
> 	at ADBSocket.connect (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/sockets/androidsocket.js:18:30)
> 	at ADBClient.connect_to_adb (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/adbclient.js:360:31)
> 	at ADBClient.list_devices (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/adbclient.js:139:20)
> 	at selectTargetDevice (/root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/src/utils/device.js:33:43)
> 	at /root/.vscode-server/extensions/adelphes.android-dev-ext-1.4.0/extension.js:161:38
> 	at Y0.h (file:///vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
> ...
> ```
