### ISSUE TITLE
Breakpoints don't trigger when hit

### ISSUE THREAD

**Issue by dave-plutoflume** [adelphes/android-dev-ext#34]
Logs show the breakpoint being hit, but nothing is shown in the editor. The issue appears to be a failed command in the JDWP.
Related to #24

**Comment by dave-plutoflume** [comment]
The issues appears to be related to retrieving the line table for the following methods:
- `MessageQueue.nativePollOnce`
- `Method.invoke`

The JDWP commands fail which in turn causes a throw when the line array is sorted.

```
/usr/share/code/code --debugBrkPluginHost=47158 --debugId=fb4296e8-6501-4ef6-80f6-170242309aef --extensionDevelopmentPath=/home/dave/dev/vscode/android-dev-ext 
/usr/bin/node --inspect-brk=21525 src/debugMain.js --server=4711 
Debugger listening on ws://127.0.0.1:21525/bae07483-468a-48a7-83b0-2f3cc90eb887
Debugger attached.
Git extension API method 'getGitPath' is deprecated.
activating extension
WebSocketServer started. Listening on port: 6037
waiting for debug protocol on port 4711
>> accepted connection from client
Launching: {"type":"android","name":"Android Debug","request":"launch","appSrcRoot":"/home/dave/AndroidStudioProjects/BasicApp/app/src/main","apkFile":"/home/dave/AndroidStudioProjects/BasicApp/app/build/outputs/apk/debug/app-debug.apk","adbPort":5037,"verboseLog":true,"debugServer":4711,"pipeName":"62f9bbfe05614a87b9ef4dc90da8e8d0","workspaceFolders":[{"uri":{"$mid":1,"fsPath":"/home/dave/AndroidStudioProjects/BasicApp","external":"file:///home/dave/AndroidStudioProjects/BasicApp","path":"/home/dave/AndroidStudioProjects/BasicApp","scheme":"file"},"name":"BasicApp","index":0}],"enableMultipleRoots":true,"__sessionId":"1bb92edf-d1cf-4447-9ce8-07092b5a86ba"}
Checking build
Searching for devices...
Found 1 device
Current build already installed
Launching com.example.dave.basicapp/.MainActivity on device ABCD12345678 [API:28]
Accepted event request: exception, id:2
Accepted event request: threadstart, id:3
Accepted event request: threadend, id:4
Continuing app start
thread start: 000000000000000c(12)
thread start: 000000000000000d(13)
thread end: 000000000000000d(13)
threadsRequest: 14
thread start: 000000000000000e(14)
threadsRequest: 15
setBreakPointsRequest: /home/dave/AndroidStudioProjects/BasicApp/app/src/main/java/com/example/dave/basicapp/MainActivity.kt
Accepted event request: breakpoint, id:5
Breakpoint hit: {"qtype":"com/example/dave/basicapp/MainActivity","linenum":14,"threadid":"0000000000000001"}
threadsRequest: 15

Command failed: error 511 jdwp.js:100
Reply {length: 11, id: 147, flags: 128, errorcode: 511, rawdata: Array(0), …} jdwp.js:100
  command:Command {length: 27, id: 147, flags: 0, …}
    command:1
    commandset:6
    deferred:Object {_isdeferred: true, _original: Promise, _promise: Promise, …}
    flags:0
    id:147
    length:27
    name:"Linetable:MessageQueue,nativePollOnce"
    rawdata:Array(16) [0, 0, 0, …]
    replydecodefn:function (o) { … }
    __proto__:Object {promise: , toRawString: , tob64: }
  errorcode:511
  flags:128
  id:147
  length:11
  rawdata:Array(0) []
  __proto__:Object {constructor: }
  null: Command failed: error 511
null: Reply {length: 11, id: 148, flags: 128, errorcode: 511, rawdata: Array(0), …}
(node:29825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sort' of undefined
    at Debugger.<anonymous> (/home/dave/dev/vscode/android-dev-ext/src/debugger.js:1430:33)
    at Object.p._promise.then.bind.def (/home/dave/dev/vscode/android-dev-ext/src/jq-promise.js:21:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:29825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sort' of undefined
    at Debugger.<anonymous> (/home/dave/dev/vscode/android-dev-ext/src/debugger.js:1430:33)
    at Object.p._promise.then.bind.def (/home/dave/dev/vscode/android-dev-ext/src/jq-promise.js:21:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:29825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```
